### ISSUE TITLE
Pod install doesn't work properly

### ISSUE THREAD

**Issue by andrewmarmion** [Ramotion/circle-menu#1]
I tried using the Pod install and even though the files copied across with the Pod it wouldn't see the files when I was setting up the CircleMenuDelegate, I kept getting an error message that CircleMenuDelegate was undefined. However, if I copied the files across to the project then it noticed it straight away and I was able to get it working :)

Not sure if I did something wrong or if the setup with the Pod isn't quite right.

**Comment by 0ber** [comment]
I updated podspec, can you try again?

**Comment by andrewmarmion** [comment]
I created an empty app to test it again, unfortunately I still have the same issue with the pod install. when I try to set up the delegate like you have in your sample app it keeps stating 

`class ViewController: UIViewController, CircleMenuDelegate {`

> Use of undeclared type 'CircleMenuDelegate'

Is there something that I have to import at the top of my class? I am guessing that I am missing a step in setting this up properly. 

What's interesting is that if I CMD + click on the words CircleMenuDelegate it takes me to the corresponding protocol in CircleMenu.swift. 

p.s. I really like this CircleMenu button.

**Comment by 0ber** [comment]
which version do you install ? need 0.0.5

**Comment by andrewmarmion** [comment]
I was using 0.05, this is my Podfile

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'circlemenutest' do
pod 'CircleMenu', '~> 0.0.5'
end
```

**Comment by 0ber** [comment]
in my case after connected pod and `import CircleMenu` i see error too, but after build (cmd + B) error is hiding (maybe it's a xcode bug??)

**Comment by andrewmarmion** [comment]
It won't let me build. It keeps coming back as a failure, with the same error

> Use of undeclared type 'CircleMenuDelegate'

**Comment by GSebastian** [comment]
Having the same problem unfortunately - "Use of undeclared type CircleMenuDelegate". Weird thing is that if I cmd-click the delegate, I see the source code.

**Comment by cblier** [comment]
I am having the same problem. using xCode 7.3.1, iOS build target 9.3 unlike andrewmarmion I cannot even drag the Lib to a project and build it that way. I get the same error when trying to add CircleMenuDelegate?

my PodFile

platform :ios, "9.3"
use_frameworks!

target 'CircleMenuTest' do
 pod 'CircleMenu', '~> 1.0.0'
end

However I can build the demo app without a problem...

**Comment by cblier** [comment]
However I can build the demo app without a problem...
