### ISSUE TITLE
Enhanement request: Buttons popup just in one side

### ISSUE THREAD

**Issue by LiborZ** [Ramotion/circle-menu#12]
Hi, I really like your menu and I have idea for improvement that could be very useful for me and with that I can use this control in my app. What about some option that buttons would show only in just half circle (180 degrees not full 360 degrees)? User could set if he wants to use control in left/right/bottom/down side of screen and buttons would be shown in visible area. I think the image would be best for explain this:
![img_3560](https://cloud.githubusercontent.com/assets/620987/14879421/7ae0ac02-0d29-11e6-89d3-711b1e58edd9.PNG)

I made just few changes to your code to try this if it would be possible and it works great. What do you think about this? Thanks

P.s.: Are you planning to distribute your menu via Carthage too?

**Comment by Nick-The-Uncharted** [comment]
+1. It's rare that we will put a button at the center of screen.

**Comment by A1exandre** [comment]
+1 my button moves around and when it is on the side of the screen, half of the menu is out of the screen's bounds. This would solve my issue.

**Comment by jasondibenedetto** [comment]
+1

**Comment by RigoOnRails** [comment]
+1

**Comment by saijunhu** [comment]
+1

**Comment by saijunhu** [comment]
@LiborZ  now i also need a 180 effect ,i want to know how change it

**Comment by yannbu** [comment]
+1

**Comment by dancemonkey** [comment]
I've been hunting through the code to try and do something similar, I'd love to know how you did this.

**Comment by caesss** [comment]
+1

**Comment by kentonraiford** [comment]
+1

**Comment by 0ber** [comment]
#48
