### ISSUE TITLE
Error: the example run failed 

### ISSUE THREAD

**Issue by saijunhu** [Ramotion/circle-menu#15]
i clone the project to local and run , i modify nothing,and build, run , the result is

2016-07-19 14:22:08.848 CircleMenuDemo[10474:246504] **\* T**erminating app due to uncaught exception 'NSInvalidArgumentException'**, reason: '-[CASpringAnimation setInitialVelocity:]: unrecognized selector sent to instance 0x7ff65c829070'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001099c2c65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010b9e2bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x00000001099ca0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x000000010992013c ___forwarding_** + 988
    4   CoreFoundation                      0x000000010991fcd8 _CF_forwarding_prep_0 + 120
    5   CircleMenuDemo                      0x000000010978b9af _TFFC14CircleMenuDemo10CircleMenuP33_3CC1F29DA948E4EC78CFD33B8964897B16showCenterButtonFT8durationSf5delaySd_T_U0_FCSo17CASpringAnimationT_ + 271
    6   CircleMenuDemo                      0x000000010978ba18 _TTRXFo_oCSo17CASpringAnimation_dT__XFo_iS__dT__ + 24
    7   CircleMenuDemo                      0x0000000109782755 _TF14CircleMenuDemo4IniturFTx5blockFT6objectx_T__x + 101
    8   CircleMenuDemo                      0x00000001097870ad _TFC14CircleMenuDemo10CircleMenuP33_3CC1F29DA948E4EC78CFD33B8964897B16showCenterButtonfT8durationSf5delaySd_T_ + 925
    9   CircleMenuDemo                      0x0000000109785474 _TFC14CircleMenuDemo10CircleMenu13buttonHandlerfCSo8UIButtonT_ + 2004
    10  CircleMenuDemo                      0x000000010978597a _TToFC14CircleMenuDemo10CircleMenu13buttonHandlerfCSo8UIButtonT_ + 58
    11  UIKit                               0x000000010a717d62 -[UIApplication sendAction:to:from:forEvent:] + 75
    12  UIKit                               0x000000010a82950a -[UIControl _sendActionsForEvents:withEvent:] + 467
    13  UIKit                               0x000000010a8288d9 -[UIControl touchesEnded:withEvent:] + 522
    14  UIKit                               0x000000010a764958 -[UIWindow _sendTouchesForEvent:] + 735
    15  UIKit                               0x000000010a765282 -[UIWindow sendEvent:] + 682
    16  UIKit                               0x000000010a72b541 -[UIApplication sendEvent:] + 246
    17  UIKit                               0x000000010a738cdc _UIApplicationHandleEventFromQueueEvent + 18265
    18  UIKit                               0x000000010a71359c _UIApplicationHandleEventQueue + 2066
    19  CoreFoundation                      0x00000001098f6431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    20  CoreFoundation                      0x00000001098ec2fd __CFRunLoopDoSources0 + 269
    21  CoreFoundation                      0x00000001098eb934 __CFRunLoopRun + 868
    22  CoreFoundation                      0x00000001098eb366 CFRunLoopRunSpecific + 470
    23  GraphicsServices                    0x000000010e7c9a3e GSEventRunModal + 161
    24  UIKit                               0x000000010a7168c0 UIApplicationMain + 1282
    25  CircleMenuDemo                      0x000000010978db42 main + 114
    26  libdyld.dylib                       0x000000010c293145 start + 1
)
**libc++abi.dylib: terminating with uncaught exception of type NSException**
(lldb)

**Comment by gaming-hacker** [comment]
this looks like swift3 code

**Comment by gaming-hacker** [comment]
check your version of swift
