### ISSUE TITLE
ios8 buttonDidSelected crash

### ISSUE THREAD

**Issue by magicowl** [Ramotion/circle-menu#19]
let rotation = Init(CASpringAnimation(keyPath: "transform.rotation")) {
      $0.duration        = NSTimeInterval(1.5)
      $0.toValue         = (0)
      $0.fromValue       = (Float(-180).degrees)
      $0.damping         = 10
      //$0.initialVelocity = 0
      $0.beginTime       = CACurrentMediaTime() + delay
    }

**Comment by RamotionRussell** [comment]
iOS8 is not supported - the docs incorrectly stated this. See https://github.com/Ramotion/circle-menu/issues/27
