### ISSUE TITLE
Support for Swift 3

### ISSUE THREAD

**Issue by jacobokoenig** [Ramotion/circle-menu#22]
Hi,

When updated to Xcode 8, and Swift 3, the animations stop working properly. The secondary button, when tapped, appears in the center (when the main menu button is), while the color animation happens.

**Comment by TripLinks** [comment]
Same here. Xcode tries to convert to Swift 3 but trips up on a few methods. Are there any plans to fix the code for Swift 3?

**Comment by nitrag** [comment]
+1
