### ISSUE TITLE
CircleMenuButton is undeclared when using delegate methods

### ISSUE THREAD

**Issue by CraigMcCahill** [Ramotion/circle-menu#32]
Delegates methods in UIViewController will not run because CircleMenuButton is undeclared. I'm using CircleMenu as a Pod.

`func circleMenu(circleMenu: CircleMenu, willDisplay button: CircleMenuButton, atIndex: Int)`

Adding a CircleMenu to the storyboard works fine. But I can't use the delegate methods.

**Comment by OrielBelzer** [comment]
Facing the same issue, anyone figured out what it is?

**Comment by CraigMcCahill** [comment]
Ok the Read Me documentation just needs updating - the button parameter is now of type UIButton - like this:

`func circleMenu(_ circleMenu: CircleMenu, buttonWillSelected button: UIButton, atIndex: Int)`

With this signature the delegate method will build. If somebody makes a PR to change the Read Me - that would avoid confusion.

**Comment by CraigMcCahill** [comment]
Re opened because the docs need updating and others might find this useful until then.

**Comment by RamotionRussell** [comment]
Yes, it should be `UIButton`, not `CircleMenuButton`. Fixed in ea82aeff84fefd5ea70fcf1c9a0c48c244fd9b19
