### ISSUE TITLE
var buttons: [UIButton] should be public

### ISSUE THREAD

**Issue by AhmadFayyas** [Ramotion/circle-menu#34]
When trying to access buttons array property, it shows a compile-time error, saying:

> "buttons" is inaccessible due to "internal" protection level 

What I had to do to fix it is to unlock the pod and let it a `public` property which is inappropriate to deal with pods.

Thank you for your efforts.

**Comment by RamotionRussell** [comment]
I think the design intent was to set buttons via `func circleMenu(_ circleMenu: CircleMenu, willDisplay button: UIButton, atIndex: Int)`. Is there a specific reason you need access to `buttons`? I can probably give you an accessor if you need it, but I don't feel comfortable exposing the property itself as public and mutable.
