### ISSUE TITLE
Button Click Not Working

### ISSUE THREAD

**Issue by Mahan3340** [Ramotion/circle-menu#39]
Hi, Button WillbeSelected is Called when a button is clicked , but DidSelected wont 
please fix it or guide me if I'm doing something wrong . 

  `func circleMenu(_ circleMenu: CircleMenu, buttonDidSelected button: UIButton, atIndex: Int) {
        print("clicked")
}`

and obviously I've extended delegate , cause other methods and customizing buttons is working .

**Comment by nitishmaropost** [comment]
Why is this closed ? The issue still remains in the latest code. Can be seen in dim project.
