### ISSUE TITLE
Swift 4 Support 

### ISSUE THREAD

**Issue by Mahan3340** [Ramotion/circle-menu#40]
Hi , there are some warnings in swift 4 please fix them

**Comment by dreed47** [comment]
+1

**Comment by jstxx** [comment]
+1

**Comment by pbeneteau** [comment]
+1

**Comment by Skyb0rg** [comment]
+1

**Comment by Asinox** [comment]
+1

**Comment by 0ber** [comment]
@Asinox Why you commented issues? 
I tested it works 
![image](https://user-images.githubusercontent.com/5435782/34975490-071b2d9c-faa3-11e7-979a-3bd9d489aef5.png)

**Comment by Asinox** [comment]
@ober01, I was thinking was a Swift 4 support, i fixed it putting the pod inside my test target...that fixed my issue...i think there is a thing to check there... i wasn't able to use this after put it inside my test target (well just like you did)

Thanks!, i love this library
