### ISSUE TITLE
sub button shape issue

### ISSUE THREAD

**Issue by justin3527** [Ramotion/circle-menu#42]
hello , first i thank you for make a good library
i have some issue

i used only basic function, but shape of sub button is strange depending on screen size
(4-inch is normal but 4.7 and 5.5 inch is strange like to under picture)

what happen? can you help me?

![2017-09-30 8 33 17](https://user-images.githubusercontent.com/23233979/31045453-5e32d842-a61f-11e7-996c-bee7f35d8553.png)
![2017-09-30 8 32 27](https://user-images.githubusercontent.com/23233979/31045454-5e359de8-a61f-11e7-8fc1-6c1644889b30.png)
![img_4565](https://user-images.githubusercontent.com/23233979/31045455-5e384cf0-a61f-11e7-9efd-25d1c66407b7.PNG)

**Comment by tache** [comment]
Since  you set your button size on line 8, you have to also rest the corner radius, add ...

`button.layer.cornerRadius = button.size.height / 2.0`

**Comment by 0ber** [comment]
for change pop button size use:
`open var subButtonsRadius: CGFloat?`
#43
