### ISSUE TITLE
Set sub buttons size programmatically 

### ISSUE THREAD

**Issue by pbeneteau** [Ramotion/circle-menu#43]
Hi, is there a way to set the sub buttons size programmatically without storyboard? Thx!

**Comment by tache** [comment]
Inside of 
`func circleMenu(_ circleMenu: CircleMenu, willDisplay button: UIButton, atIndex: Int) { ... }`

do 

`button.size = CGSize(width: 100.0, height: 100.0)`

You will want to set the radius as well for circles ... 
 
`button.layer.cornerRadius = button.size.height / 2.0`

**Comment by 0ber** [comment]
@tache it is the wrong solution 
![screen recording 2018-01-22 at 12 01 pm](https://user-images.githubusercontent.com/5435782/35212743-3940a4be-ff6c-11e7-917a-b1ccf5b3d926.gif)

**Comment by 0ber** [comment]
use:  `open var subButtonsRadius: CGFloat?`
