### ISSUE TITLE
How can I have some padding around the images in a small circle menu?

### ISSUE THREAD

**Issue by Sweeper777** [Ramotion/circle-menu#53]
For my app, I want to add a smaller circle menu, not as big as the one shown in the demo. Its width and height are 32x32.

When i resize the menu button in the storyboard, the menu buttons that pops up is smaller as well, which is what I expected. However, the images on the button are still as big. This means that he nice padding around the images is gone, and the button looks like this:

<img width="43" alt="2018-04-18 8 17 00" src="https://user-images.githubusercontent.com/13585047/38917263-22b62930-42e2-11e8-97b2-4201261e504b.png">

I tried to manually add some transparent padding on the image, but the result stayed the same.

**Comment by 0ber** [comment]
in version 3.0.6 I made properties `customNormalIconView`, `customSelectedIconView` public 
and now you can set icon size:
```swift
        CIRCLE_BUTTON.customNormalIconView?.frame.size = SIZE
        CIRCLE_BUTTON.customNormalIconView?.contentMode = .scaleAspectFit
        CIRCLE_BUTTON.customSelectedIconView?.frame.size = SIZE
        CIRCLE_BUTTON.customSelectedIconView?.contentMode = .scaleAspectFit
```

**Comment by Sweeper777** [comment]
Is the `CIRCLE_BUTTON` referring to the `CircleMenu` object that I am using or the `UIButton` object passed to the delegate method `willDisplayButton`?

**Comment by 0ber** [comment]
Yes `CIRCLE_BUTTON` is a referring to the CircleMenu, and you can set size in `viewdidload`
