### ISSUE TITLE
NativeScript Circular Menu Plugin for Android

### ISSUE THREAD

**Issue by sujitbulu** [Ramotion/circle-menu#59]
Hi - First of all thanks for releasing the plugin, Circular Menu in NativeScript. I believe the plugin is intended to design to run in for iOS, the plugin - nativescript-circular-menu is not working for Android. Could any one please let know if there any plan of releasing it for Android in any period of time.

Thanks
Sujit

**Comment by 0ber** [comment]
https://github.com/Ramotion/react-native-circle-menu
https://github.com/Ramotion/android-ui-animation-c
