### ISSUE TITLE
Menu icon position

### ISSUE THREAD

**Issue by hieunc229** [Ramotion/circle-menu#6]
It's a pretty great component but I rarely see that we have the menu icon in the middle of the page
So could we move the icon somewhere (up top left) and animate items in different places?

Really appreciate your work!

**Comment by cuongnguyenta** [comment]
Absolutely! You just change position x,y of the button. Here is code: 

```
let button = CircleMenu(
  frame: CGRect(x: 200, y: 200, width: 50, height: 50),
```

You should read the document before ask question.
