### ISSUE TITLE
Add tap gesture recognizer on view to close the menu

### ISSUE THREAD

**Issue by Jackson0111** [Ramotion/circle-menu#9]
Great work! I was just wondering if there was a function that I can call to close the menu without selecting ? For example, I would like to add a tap gesture recognizer on self.view so that users can close the menu by tapping anywhere on the screen.

**Comment by 0ber** [comment]
added method `public func hideButtons(duration: Double, hideDelay: Double = 0)`

**Comment by Jackson0111** [comment]
AWESOME! Just a stupid question, but I did pod install but couldn't find this function, any idea why that's happening? I just ended up adding hideButtons in my own pod

**Comment by 0ber** [comment]
pod update )

**Comment by Jackson0111** [comment]
Thanks! Great! I think having a didDisplay delegate function would be good, because I'm adding a tap gesture but I want to remove it when the menu is closed so that the view can pick up other gesture recognizers to do something else.
